services:
  frontend:
    build: my-app
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./my-app:/usr/src/app
      - /usr/src/app/node_modules
    container_name: frontend
    restart: always
